### ISSUE TITLE
page "Sending an Ajax Request" in chapter 13 of Java EE edition 8 is not displayed well

### ISSUE THREAD

**Issue by shadyar** [eclipse-ee4j/jakartaee-tutorial#144]
a page in chapter 13 of Java EE edition 8 is not displayed well. it
looks like markup codes.

https://eclipse-ee4j.github.io/jakartaee-tutorial/jsf-ajax004.html

**Comment by ivargrimstad** [comment]
I believe this issue has been fixed with the latest release of the tutorial, https://eclipse-ee4j.github.io/jakartaee-tutorial/.
