### ISSUE TITLE
This page does not have any HTML tag heading 

### ISSUE THREAD

**Issue by shadyar** [eclipse-ee4j/jakartaee-tutorial#184]
This page does not have any HTML tag heading 
Chapter: 36
Title: Modifying the Jakarta EE Application
url: https://eclipse-ee4j.github.io/jakartaee-tutorial/ejb-gettingstarted003.html

**Comment by nehrusingh** [comment]
I made one change today to fix the content

**Comment by keilw** [comment]
In a PR?

**Comment by nehrusingh** [comment]
yes PR , Just committed few minutes back.
