### ISSUE TITLE
Lagging far behind Jakarta EE

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/jakartaee-tutorial#186]
At the moment both this tutorial and the examples lag far behind Jakarta EE itself. While the Jakarta repositories are heading towards `9.0.0-SNAPSHOT` or similar, this has not even reached a stable 8.0 release.

In future this should be more coordinated.

**Comment by ggam** [comment]
We need to resolve the Java EE references on images issue before publishing a final release...

**Comment by keilw** [comment]
Is that a legal issue or just availability of resources?

**Comment by ggam** [comment]
I guess this can be closed now.
