### ISSUE TITLE
It is not possible to see table of contents and documentation at the same time.

### ISSUE THREAD

**Issue by pjmlp** [eclipse-ee4j/jakartaee-tutorial#187]
While the Sun original tutorial J2EE and JEE series, and respective Oracle ones, allowed for split screen containing both TOC and current contents, the JakartaEE variant only shows the contents.

This adds an extra pain to the navigation.

The previous Java EE7 tutorial shows it properly, https://docs.oracle.com/javaee/7/index.html

![image](https://user-images.githubusercontent.com/608876/73256576-71631080-41c2-11ea-8d34-ed0ca2003bc2.png)

![image](https://user-images.githubusercontent.com/608876/73256619-8475e080-41c2-11ea-9fa9-6493677cdc9e.png)

**Comment by ggam** [comment]
Hi @pjmlp I'm working on a PR to convert the whole tutorial to standard AsciiDoc which would render similar to http://www.ggam.eu/jakartaee-firstcup/firstcup.html (see PR on [FirstCup](https://github.com/eclipse-ee4j/jakartaee-firstcup/pull/13)). From there we'll be able to easily improve stilyng. I particularly like Hibernate documentation navigation: https://docs.jboss.org/hibernate/orm/current/userguide/html_single/Hibernate_User_Guide.html

**Comment by ggam** [comment]
Please have a look at #191

**Comment by pjmlp** [comment]
Hi @ggam thanks for the update, I had a look at #191 and the result already looks quite good!

Congratulations on the work.
