### ISSUE TITLE
broken links 

### ISSUE THREAD

**Issue by nehrusingh** [eclipse-ee4j/jakartaee-tutorial#188]
Few broken link in the below URL

https://eclipse-ee4j.github.io/jakartaee-tutorial/ejb-async.html

 link:ejb-async001.html#GKKQG[Asynchronous Method Invocation]
* link:ejb-async002.html#GKIEZ[The async Example Application]

**Comment by ggam** [comment]
#191 solves this.

**Comment by ggam** [comment]
This can be closed

**Comment by arjantijms** [comment]
Closing issue, thanks @ggam
