### ISSUE TITLE
Markup typo's in overview008.adoc

### ISSUE THREAD

**Issue by arnovh** [eclipse-ee4j/jakartaee-tutorial#190]
Headings :
- Jakarta RESTful Web Services
- Jakarta Contexts and Dependency Injection

in section overview008.adoc are not formatted correctly.
I never wrote asciidoc but is seems they have to many ~ below them.

Thanks for creating this document.

**Comment by ggam** [comment]
#191 solves this

**Comment by ggam** [comment]
This issue can now be closed.
