### ISSUE TITLE
Naming on contributing page

### ISSUE THREAD

**Issue by jgallimore** [eclipse-ee4j/jakartaee-tutorial#197]
from: https://github.com/jakartaee/jakarta.ee/issues/851

Please CUT the Eclipse word that happens two times on this page https://eclipse-ee4j.github.io/jakartaee-tutorial/CONTRIBUTING:

- Contributing to Jakarta EE Platform

Eclipse must never be added before Jakarta EE. Jakarta EE is a stand alone project under the ee4j umbrella.

PR is available here: https://github.com/eclipse-ee4j/jakartaee-tutorial/pull/196

**Comment by aeiras** [comment]
Thank YOU @jgallimore!

**Comment by ggam** [comment]
This can be closed now
