### ISSUE TITLE
Namespace sample in What Is Facelets?

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/jakartaee-tutorial#218]
https://eclipse-ee4j.github.io/jakartaee-tutorial/jsf-facelets001.html

>xmlns:composite="http://java.sun.com/jsf/composite"

>instead of as

>xmlns:cc="http://java.sun.com/jsf/composite"

Should update to use JCP in Jakarta EE 8???

**Comment by arjantijms** [comment]
Sounds good!
