### ISSUE TITLE
Format issue  Developing with Jakarta Server Faces Technology

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/jakartaee-tutorial#220]
https://eclipse-ee4j.github.io/jakartaee-tutorial/jsf-develop.html

**Comment by keilw** [comment]
Would you or someone else be able to create a PR for that?

**Comment by hantsy** [comment]
Of course I can submit a pr later. 
Now go througth the whole doc.

**Comment by keilw** [comment]
Thanks, are you a committer or have signed the ECA?

**Comment by hantsy** [comment]
I have signed the ECA in before small fixes

**Comment by hantsy** [comment]
@keilw The https://eclipse-ee4j.github.io/jakartaee-tutorial deployed the latest version of docs? 

I compiled it on my local machine, the format seems good. And the HTML layout is different from https://eclipse-ee4j.github.io/jakartaee-tutorial.
