### ISSUE TITLE
Format issue in Modifying the Jakarta EE Application

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/jakartaee-tutorial#223]
https://eclipse-ee4j.github.io/jakartaee-tutorial/ejb-gettingstarted003.html

**Comment by ggam** [comment]
The format is already fixed in the master branch, but the deployed site hasn't been updated in a while. You can look at the current version at http://ggam.github.io/jakartaee-tutorial/#modifying-the-jakarta-ee-application

**Comment by hantsy** [comment]
Thanks @ggam
