### ISSUE TITLE
Format issue in Jakarta Concurrency

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/jakartaee-tutorial#227]
https://eclipse-ee4j.github.io/jakartaee-tutorial/concurrency-utilities.html

**Comment by ggam** [comment]
@hantsy the whole content of the tutorial has been revised on #239. I guess most of the format issues you reported are already fixed now. Would you please confirm and close the outdated ones?

**Comment by hantsy** [comment]
@ggam Thanks.
