### ISSUE TITLE
Add a Github  workflow to deploy docs automaticially

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/jakartaee-tutorial#231]
Hope to add a GitHub action workflow to automate the deployment to Github pages.

* When Pr is merged in the master to deploy a snapshot version.
* When the repo is tagged with a version, deploy a versioned release via a different URL.

**Comment by ggam** [comment]
The deployed `gh-pages` branch is already way behind `master`. Does anybody know how is this managed and whether we could do at least a manual redeploy right now?
