### ISSUE TITLE
jakartaee-tutorial-examples in not building throwing error datasource 

### ISSUE THREAD

**Issue by rajshailesh** [eclipse-ee4j/jakartaee-tutorial#245]
When building jakartaee-tutorial then throwing following error....

> Cannot connect to database via JNDI name 'java:comp/DefaultDataSource'

Do we need to create JNDI resource before running mvn install command ?
Also documentation to run the tutorial will be helpful
I am facing other problem also when I am executing main method of Producer and Consumer java classes under JMS project

**Comment by bvfalcon** [comment]
> Do we need to create JNDI resource before

Of course no. I try now "mvn install" execute and all works ok. May be changes in your fork make this error?

**Comment by rajshailesh** [comment]
I am using Windows 10 for development. Firstly I cloned master branch then I tried other branch too EE4J_8. I am running glassfish5 and changed glassfish home path in pom.xml accordingly. When building on later branch then getting some SQL exception in ALTER command

**Comment by rajshailesh** [comment]
This is repository for tutorial (doc). Therefore closing here and will open in jakartaee-tutorial-examples repo
