### ISSUE TITLE
Release 9.1 final at or shortly before 2021-05-17

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/jakartaee-tutorial#253]
The Jakarta EE 9.1 release is targeted at 2021-05-17. It would be great if we can have the final release of the 9.1 tutorial at, or shortly before, that date so as to join the 9.1 release train.

cc @keilw @ggam @hussainnm @hantsy

**Comment by keilw** [comment]
@arjantijms You mean skip 9.0?
It took us over a year before we finally tagged off 8.1 which corresponds to Jakarta EE 8.0 so first we should get to 9.0, if the upgrade to 9.1 then works reasonably fast, why not but I would not skip 9.0 as the products only compatible with 9.0 just started to add up: https://jakarta.ee/compatibility/#tab-9
Therefore I would not stick to an official Jakarta EE 9.1 code-freeze at least not this time because that's a week from now, let's do 9.0 first whenever we can and then 9.1.

**Comment by hantsy** [comment]
9.1 is not a big update, in the tutorial just needs to add a section to describe the changes in Jakarta EE 9.1, esp. the Java 11 support, more deprecated APIs for attention.
I do not think it is a must to separate the  9.0 and 9.1 in the different tutorial docs.

**Comment by keilw** [comment]
In the actual tutorial I guess not, in the examples, I cannot say because it also takes dependencies like a BOM or Jakarta API.
Maybe the 9.0 tutorial could end up with more than one 9.x example if the tutorial itself won't really change.

**Comment by ggam** [comment]
From my side, I think the release for 9.0 can be started now. That way we
can start working on 9.1 in case we find some changes are needed.

**Comment by arjantijms** [comment]
Officially the one and only change is that it MUST be possible to certify an implementation using JDK 11.

JDK 8 is still fully supported and even mandated for the APIs. No functionality has been added for Jakarta EE 9.1. The maven coordinates for the platform pom changed to 9.1 but effectively these too are identical.

So for the tutorial, everything that holds for 9 also holds for 9.1.

**Comment by arjantijms** [comment]
@hussainnm I'll merge the PR in so that we can hopefully finally release this ;)

It's only a few months until Jakarta EE 10 is targeted to be released, so would be good to have the tutorial no more than 1 major version behind.

**Comment by arjantijms** [comment]
@hussainnm @keilw @ggam The PR is finally merged, shall we go ahead to release this?

**Comment by ggam** [comment]
Yeah, I think it's good to go.

**Comment by arjantijms** [comment]
@ggam perfect! Are you able to do this actual release? I mean, do you know how to do it?
