### ISSUE TITLE
Two more small corrections in "Packaging and Deploying the hello1 Web Module" section.

### ISSUE THREAD

**Issue by DmitriGit** [eclipse-ee4j/jakartaee-tutorial#257]
The section "Packaging and Deploying the hello1 Web Module" (https://eclipse-ee4j.github.io/jakartaee-tutorial/#packaging-and-deploying-the-hello1-web-module) has two subsections:

"_To Build and Package the hello1 Web Module Using NetBeans IDE_"
and 
"_To Build and Package the hello1 Web Module Using Maven_"

Because these subsections include information about a deploy also, I think it's more correctly that the sections names should be:
"_To Build, Package and **Deploy** the hello1 Web Module Using NetBeans IDE_"
and 
"_To Build, Package and **Deploy** the hello1 Web Module Using Maven_"

Thank you,
Dmitri.

**Comment by arjantijms** [comment]
If possible, a PR would be much preferred ;)

**Comment by DmitriGit** [comment]
Yes, sure! Thank you!
